version: '3.4'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "softinven1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql    

  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: WebUI/Dockerfile
    container_name: softinven
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=softinven;User=sa;Password=softinven1234;
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app

volumes:
  sqlserverdata:
